export const SelectTravelList = [
  {
    id: 1,
    title: "Travel 1",
    description: "This is a sample travel description",
    image: "https://example.com/image1.jpg",
    price: 200,
    duration: 10,
    destination: "Destination 1",
  },
  {
    id: 2,
    title: "Travel 2",
    description: "This is another sample travel description",
    image: "https://example.com/image2.jpg",
    price: 300,
    duration: 15,
    destination: "Destination 2",
  },
  {
    id: 3,
    title: "Travel 3",
    description: "This is yet another sample travel description",
    image: "https://example.com/image3.jpg",
    price: 400,
    duration: 20,
    destination: "Destination 3",
  },
  {
    id: 4,
    title: "Travel 4",
    description: "This is a fourth sample travel description",
    image: "https://example.com/image4.jpg",
    price: 500,
    duration: 25,
    destination: "Destination 4",
  },
  {
    id: 5,
    title: "Travel 5",
    description: "This is a fifth sample travel description",
    image: "https://example.com/image5.jpg",
    price: 600,
    duration: 30,
    destination: "Destination 5",
  },
  {
    id: 6,
    title: "Travel 6",
    description: "This is a sixth sample travel description",
    image: "",
    price: 700,
    duration: 35,
    destination: "Destination 6",
  },
];
